version: '3.8'
services:
  api:
    container_name: api
    build:
      context: ./api/
      target: ${MODE}
    volumes:
      - ./api/:/usr/src/app
  modelapi:
    container_name: modelapi
    build:
      context: ./modelapi/
      target: ${MODE}
    volumes:
      - ./modelapi/:/usr/src/app
    command: flask --app server run --port 8000 --host 0.0.0.0 --debug
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
    volumes:
      - ./frontend/:/app/
  webserver:
    image: nginx:1.25.3
    container_name: webserver
    volumes:
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./api/plotter/uploads/:/usr/src/plots
      - ./api/static:/usr/src/static
    ports:
      - 80:80
      - 443:443


      


